### PR TITLE
Push AMIs to various regions

### PR DESCRIPTION
**Pull request by jvanderhoof**
@dustinmm80: A job to push AMI's out to the various regions.

### CODE REVIEW

**Comment by jvanderhoof** [comment]
Looks like the Docker image needed to run this is never published.  I get that resolved to insure this can work for real.

**Comment by dustinmm80** [comment]
Yeah let's have less try and put less logic in Jenkins shell and not more. It's also unclear if this script really works or not - needs to be verified.

**Comment by kgilpin** [comment]
@jvanderhoof @dustinmm80 please take a fresh look at this.

**Comment by dustinmm80** [comment]
I'm going to close this. To further automate appliance release we should create a separate pipeline that does all the release steps after appliance pipeline has produced a stable image.

**Pull request closed without merging**
